### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by shotawashino** [shotawashino/chat-space#9]
# IPアドレス
13.112.207.82

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

### [修正箇所]
①グループを作成して１回目のメッセージ送信で自動更新ができるようにしましょう
<img width="1431" alt="自動更新" src="https://user-images.githubusercontent.com/49669977/86429552-e49d1f80-bd2a-11ea-834f-32471b05c211.png">

修正が完了次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by shotawashino** [comment]
ご指摘ありがとうございます。
初回メッセージの同期ができるように修正しました。
ご確認、よろしくお願いします。

**Comment by mutorisa** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！

⭐️今後実装に関するご質問がございましたら、メンターに相談いただきますようお願いします。

**Comment by shotawashino** [comment]
ありがとうございます！
これからもがんばりますのでよろしくお願いします！

**Comment by mutorisa** [comment]
誤って削除してしまった為、再送させていただきます。
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！

⭐️今後実装に関するご質問がございましたら、メンターに相談いただきますようお願いします。
